tasks:
  - name: workshop-astra-tik-tok
    init: |
      cd /workspace/workshop-astra-tik-tok 
      nvm install node
      npm install -g npm@latest
    command: |
      cd /workspace/workshop-astra-tik-tok
      echo "
     ___           _______.___________..______          ___         .___________. __   __  ___ .___________.  ______    __  ___ 
    /   \         /       |           ||   _  \        /   \        |           ||  | |  |/  / |           | /  __  \  |  |/  / 
   /  ^  \       |   (----`---|  |----`|  |_)  |      /  ^  \       `---|  |----`|  | |  '  /  `---|  |----`|  |  |  | |  '  /  
  /  /_\  \       \   \       |  |     |      /      /  /_\  \          |  |     |  | |    <       |  |     |  |  |  | |    <   
 /  _____  \  .----)   |      |  |     |  |\  \----./  _____  \         |  |     |  | |  .  \      |  |     |  `--'  | |  .  \  
/__/     \__\ |_______/       |__|     | _| `._____/__/     \__\        |__|     |__| |__|\__\     |__|      \______/  |__|\__\ 
                                                                                                                                
"
      echo "workshop-astra-tik-tok gitpod ready - LET'S DO THIS!"
      npm install
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false
ports:
  - port: 8888
    onOpen: open-preview
  - port: 3000
    onOpen: ignore    
